version: '3'
services:
  node:
    container_name: portfolio_node
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    command: sh -c "yarn start"
    ports:
     - "3030:3000"
    stdin_open: true