version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:14
orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  setup_and_buid:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
              - node_modules
      - run:
          name: Build
          command: yarn build
      - save_cache:
          key: dependency-cache-dist
          paths:
            - dist

  deploy:
    executor:
      name: default
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-dist
      - aws-s3/sync:
          from: ./dist/
          to: 's3://rainier.com/'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup_and_buid
      - deploy:
          requires:
          - setup_and_buid