version: 2.1
executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:14
orbs:
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install
  build:
    executor:
      name: default
    steps:
      - run:
          name: Build
          command: yarn build
  deploy:
    executor:
      name: default
    steps:
      - aws-s3/sync:
          from: ./dist/
          to: 's3://rainier.com/'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          requires:
          - setup
      - deploy:
          requires:
          - build