version: 2.1
executors:
  default:
    working_directory: ~/workspace/frontend
    docker:
      - image: circleci/node:14
orbs:
  aws-cli: circleci/aws-cli@2.0.0

jobs:
  setup:
    working_directory: ~/workspace
    docker:
      - image: circleci/node:14
    steps:
      - run:
          name: Install dependencies
          command: yarn install
  build:
    executor:
      name: default
    steps:
      - run:
          name: Build
          command: yarn build
  deploy:
    executor:
      name: default
    steps:
      - run:
          name: Deploy
          command: aws s3 sync ./dist/ s3://rainier.com/
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          requires:
          - setup
      - aws-cli/install
      - deploy:
          requires:
          - aws-cli/install
          - build