version: 2.1
executors:
  default: &defaults
    working_directory: ~/workspace
    docker:
      - image: circleci/node:14
orbs:
  aws-s3: circleci/aws-s3@2.0.0

filter_only_main: &filter_only_main
  filters:
    branches:
      only: main

jobs:
  setup:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
              - node_modules
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - ./*
  build:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - dist

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/workspace
      - aws-s3/sync:
          from: ./dist/
          to: 's3://rainier.com/'
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - setup
      - build:
          <<: *filter_only_main
          requires:
          - setup
      - deploy:
          <<: *filter_only_main
          requires:
            - build
            - setup